let g:syntastic_cpp_compiler="gcc-4.8"
let g:syntastic_cpp_compiler_options=" -std=c++11 -lstdc++ -fopenmp"
let g:syntastic_cpp_include_dirs = [ 'src', 
            \'src/common/', 
            \'src/bie3d/', 
            \'src/bdry3d/', 
            \'src/fmm3d/', 
            \'src/deps/', 
            \'tests/results',
            \'utils/pvfmm-utils',
            \$PVFMM_DIR.'/include/',
            \$VTK_DIR.'/'.$VTK_INC_DIR,
            \'/usr/local/include/c++/4.8.5/',
            \$BLENDSURF_DIR,
            \$FACEMAP_DIR.'/src',
            \$PETSC_DIR.'/include', 
            \$PETSC_DIR.'/'.$PETSC_ARCH.'/include',
            \$MPI_HOME.'/include/',
            \$FFTW_DIR.'/include',
            \$P4EST_DIR.'/sc/include',
            \$GEOGRAM_DIR.'/src/lib',
            \$P4EST_DIR.'/include',
            \]
            "\'/usr/local/include/c++/4.8.5/',
