name: push docker image
on: 
  push:
    paths: 
      - 'Dockerfile'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Publish Build Image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mmorse1217/hedgehog
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        dockerfile: Dockerfile
        buildoptions: "--target hedgehog-deps --cache-from='mmorse1217/hedgehog:latest'"
    - name: Publish Dev Image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mmorse1217/hedgehog-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        dockerfile: Dockerfile
        buildoptions: "--target hedgehog-dev --cache-from='mmorse1217/hedgehog:latest'"
